name: speedscale-operator
home: https://speedscale.com
version: 2.5.72
description: Stress test your APIs with real world scenarios.  Collect and replay traffic without scripting.
keywords:
- speedscale
- test
- testing
- regression
- reliability
- load
- replay
- network
- traffic
maintainers:
- name: Speedscale Support
  email: support@speedscale.com
icon: https://raw.githubusercontent.com/speedscale/assets/main/logo/gold_logo_only.png
apiVersion: v1
appVersion: 2.5.72
annotations:
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: Speedscale Operator
  catalog.cattle.io/release-name: speedscale-operator
kubeVersion: ">= 1.17.0-0"
